version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=calliper
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2m
      timeout: 30s
      retries: 3
